<a href="https://colab.research.google.com/github/AxisAngeles/Smart_Data_DS_AI/blob/main/Ejercicios_ML_Sup_NoSup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1) Librerías
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score


from sklearn.datasets import load_breast_cancer, load_diabetes, fetch_california_housing
# Load and return the breast cancer Wisconsin dataset (classification).
# Load and return the diabetes dataset (regression).
# Load the California housing dataset (regression).

In [51]:
# 1) Crear DataFrames
data = load_diabetes()
print(f'Keys: {data.keys()}')

# 1.1) DIABETES
df_diabetes = pd.DataFrame(columns=data.feature_names, data=data.data)
df1 = pd.DataFrame(columns=["target"], data=data.target)
df_diabetes = pd.concat([df_diabetes,df1], axis=1)
print(f'Diabetes shape: {df_diabetes.shape}')

# 1.2) BREAST CANCER
data = load_breast_cancer()
df_breastc = pd.DataFrame(columns=data.feature_names, data=data.data)
df1 = pd.DataFrame(columns=["target"], data=data.target)
df_breastc = pd.concat([df_breastc,df1], axis=1)
print(f'Breast Cancer shape: {df_breastc.shape}')

Keys: dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])
Diabetes shape: (442, 11)
Breast Cancer shape: (569, 31)

In [48]:
df_diabetes.head(3)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0

In [49]:
df_breastc.head(3)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.0,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.5,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0